import os
import json
import logging
import asyncio
import time
import uuid
import mimetypes
import httpx
from contextlib import asynccontextmanager, AsyncExitStack
from fastapi import FastAPI, HTTPException, Response, Request
from fastapi.responses import StreamingResponse, FileResponse

from pydantic import BaseModel, Field
from typing import Optional, Dict, Any

from config import get_settings
from agent.logger import setup_logging
from agent.db import RemoteQueryExecutor
from agent.sandbox import PooledSandbox
from agent.llm import LLM
from agent.core import Agent
from agent.session_manager import SessionManager
from agent.asset_manager import AssetManager
from agent.events import SSETransport
from agent.errors import stream_error
from agent.logger import request_id_var, client_id_var, trace_id_var
from agent.auth import key_store
from agent.audit_forwarder import configure_forwarder, get_forwarder, submit_event

logger = logging.getLogger(__name__)


class QueryRequest(BaseModel):
    model_config = {"populate_by_name": True}

    query: str
    session_id: Optional[str] = None
    client_id: str
    datasource_id: Optional[str] = None
    schema_version: Optional[str] = None
    db_schema: Optional[Dict[str, Any]] = Field(default=None, alias="schema")
    sensitive_rules: Optional[Dict[str, Any]] = None
    execution: Optional[Dict[str, Any]] = None
    agent_style: Optional[Dict[str, Any]] = None
    user_ref: Optional[int] = None
    user_access: Optional[Dict[str, Any]] = None
    # This instance's data-plane URL. Python calls back here for SQL execution.
    data_plane_url: Optional[str] = None
    # This instance's turn-completion URL (billing + transcript archive). Same
    # host as data_plane_url, different path.
    completion_url: Optional[str] = None
    # JWT-like delegation token signed by the client instance, authorizing
    # Python to call the data-plane. Bound to client_id + session_id.
    delegation_token: Optional[str] = None
    # End-to-end trace id (generated by Laravel per analyze); also forwarded
    # via the X-Trace-Id header by Laravel's proxy.
    trace_id: Optional[str] = None


settings = get_settings()
setup_logging(settings.AUDIT_LOG_FILE, settings.LOG_LEVEL)

llm = LLM()


class DelegationStore:
    """Per-session delegation tokens authorizing data-plane calls.

    Keyed by (client_id, session_id). Tokens are short-lived JWT-like strings
    signed by the client instance. The executor looks up the token by session
    and forwards it to Laravel instead of signing requests itself.
    """

    def __init__(self) -> None:
        self._tokens: dict[tuple[str, str], str] = {}

    def store(self, client_id: str, session_id: str, token: str) -> None:
        self._tokens[(client_id, session_id)] = token

    def get(self, client_id: str, session_id: str) -> str | None:
        return self._tokens.get((client_id, session_id))

    def remove(self, client_id: str, session_id: str) -> None:
        self._tokens.pop((client_id, session_id), None)

    def purge_session(self, session_id: str) -> None:
        self._tokens = {k: v for k, v in self._tokens.items() if k[1] != session_id}


_EXECUTOR_IDLE_TTL_SEC = 1800  # close executors idle (no active streams) for 30+ min


class ExecutorCache:
    """Reference-counted, URL-keyed executor cache with idle eviction.

    Each active analysis stream holds a ref via acquire()/release(). When the
    last ref drops, an idle timer starts; a background sweep closes and removes
    executors past the TTL. Pop-before-await in evict_idle closes the TOCTOU
    race: a concurrent acquire() after the pop just builds a fresh executor
    rather than bumping a doomed one's refcount.
    """

    def __init__(self, delegation_store: DelegationStore):
        self._delegation_store = delegation_store
        self._executors: dict[str, RemoteQueryExecutor] = {}
        self._refcount: dict[str, int] = {}
        self._last_idle: dict[str, float] = {}

    def acquire(self, url: str, client_id: str) -> RemoteQueryExecutor:
        url = (url or "").rstrip("/")
        if url not in self._executors:
            self._executors[url] = RemoteQueryExecutor(
                base_url=url,
                delegation_store=self._delegation_store,
            )
            logger.info("ExecutorCache: new executor for %s (client=%s)", url, client_id)
        self._refcount[url] = self._refcount.get(url, 0) + 1
        self._last_idle.pop(url, None)
        logger.debug("ExecutorCache: acquire %s (refs=%d)", url, self._refcount[url])
        return self._executors[url]

    def release(self, url: str) -> None:
        url = (url or "").rstrip("/")
        if url in self._refcount:
            self._refcount[url] = max(0, self._refcount[url] - 1)
            if self._refcount[url] == 0:
                self._last_idle[url] = time.monotonic()
            logger.debug("ExecutorCache: release %s (refs=%d)", url, self._refcount[url])

    async def evict_idle(self) -> None:
        now = time.monotonic()
        for url in list(self._executors.keys()):
            if self._refcount.get(url, 0) > 0:
                continue
            if now - self._last_idle.get(url, now) <= _EXECUTOR_IDLE_TTL_SEC:
                continue
            # Pop BEFORE await so a concurrent acquire() can't resurrect this entry.
            executor = self._executors.pop(url)
            self._refcount.pop(url, None)
            self._last_idle.pop(url, None)
            await executor.close()
            logger.info("ExecutorCache: evicted idle executor for %s", url)

    async def close(self) -> None:
        for ex in self._executors.values():
            await ex.close()
        self._executors.clear()
        self._refcount.clear()
        self._last_idle.clear()


delegation_store = DelegationStore()


executor_cache = ExecutorCache(delegation_store)


# ── Turn completion reporting (billing) ────────────────────────────────────
# Python is the single, authoritative reporter of turn completion. When a turn
# finishes, it POSTs the usage deltas to the client's Laravel instance. The
# endpoint dedupes on turn_uuid (unique index), so retries here are
# idempotent. This decouples billing from the SSE relay: a cut stream can no
# longer silently drop usage rows.

_completion_tasks: set = set()


def _completion_payload(meta: dict, client_id: str, session_id: str, user_ref: Optional[int]) -> dict:
    return {
        "client_id": client_id,
        "session_id": session_id,
        "user_ref": user_ref,
        "turn_uuid": meta.get("turn_uuid", ""),
        "usage": {
            "turn_tokens": meta.get("turn_tokens"),
            "turn_prompt_tokens": meta.get("turn_prompt_tokens"),
            "turn_completion_tokens": meta.get("turn_completion_tokens"),
            "turn_reasoning_tokens": meta.get("turn_reasoning_tokens"),
            "turn_cache_hit_tokens": meta.get("turn_cache_hit_tokens"),
            "turn_cache_miss_tokens": meta.get("turn_cache_miss_tokens"),
            "turn_cost_usd": meta.get("turn_cost_usd"),
        },
    }


async def _report_turn_completion(completion_url: str, delegation_token: str, payload: dict) -> None:
    headers = {
        "X-Delegation-Token": delegation_token,
        "Content-Type": "application/json",
        "Accept": "application/json",
    }
    tid = trace_id_var.get()
    if tid and tid != "-":
        headers["X-Trace-Id"] = tid
    for attempt in range(1, 4):
        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.post(completion_url, headers=headers, json=payload)
            if resp.status_code < 400:
                logger.info("Turn completion reported | turn=%s status=%d", payload.get("turn_uuid"), resp.status_code)
                return
            logger.warning(
                "Turn completion rejected | turn=%s status=%d body=%.300s",
                payload.get("turn_uuid"), resp.status_code, resp.text or "",
            )
        except Exception as e:
            logger.warning(
                "Turn completion failed (attempt %d/3) | turn=%s | %s",
                attempt, payload.get("turn_uuid"), e,
            )
        if attempt < 3:
            await asyncio.sleep(0.5 * attempt)
    logger.error("Turn completion permanently failed | turn=%s | url=%s", payload.get("turn_uuid"), completion_url)


def _spawn_completion(meta: dict, req: QueryRequest, session_id: str) -> None:
    if not req.completion_url:
        return
    payload = _completion_payload(meta, req.client_id, session_id, req.user_ref)
    if not payload["turn_uuid"]:
        return
    task = asyncio.create_task(_report_turn_completion(req.completion_url, req.delegation_token, payload))
    _completion_tasks.add(task)
    task.add_done_callback(_completion_tasks.discard)


def _resolve_backend(setting: str, local_cls, **kwargs):
    # Only LOCAL is implemented. Fail loudly at startup on anything else rather
    # than silently running with no backend (which crashed later with confusing
    # NoneType errors).
    if setting != "LOCAL":
        raise ValueError(f"Unsupported backend '{setting}' for {local_cls.__name__}; only LOCAL is implemented")
    return local_cls(**kwargs)


# AssetManager is the SINGLE DataFrame store owner AND the plot/CSV asset
# provider. One instance is shared by both SessionManager (df persistence) and
# the Agent (plot/CSV serving), so <client>/<session>/dfs lives under the same
# root as assets and session.json.
asset_manager = _resolve_backend(settings.STORAGE_BACKEND, AssetManager,
                                 assets_dir=settings.SESSION_DIR, ttl_hours=settings.ASSETS_TTL_HOURS,
                                 base_url=settings.ASSETS_BASE_URL)

session_manager = _resolve_backend(settings.CLIENT_STORE_BACKEND, SessionManager,
                                    base_dir=settings.SESSION_DIR,
                                    ttl_minutes=settings.SESSION_IDLE_MEMORY_MINUTES,
                                    retention_days=settings.SESSION_RETENTION_DAYS,
                                    dataframe_store=asset_manager)

sandbox = PooledSandbox()

agent = Agent(sandbox, llm, session_manager=session_manager, asset_manager=asset_manager)
sse_transport = SSETransport()


async def _verify_request(request: Request, require_admin: bool = False, client_id_override: str | None = None) -> dict:
    """Verify the Ed25519 signature on a request and return the parsed JSON body.

    Reads the raw body, recomputes the signed canonical string from the
    X-Timestamp header, and verifies against the caller's registered public key.
    Returns 403 on any failure (missing/expired headers, unknown caller, bad
    signature). When ``require_admin`` is True the caller must be the admin
    instance.

    ``client_id_override`` lets callers supply the client_id out-of-band (e.g.
    from the URL path for GET requests with no body). When provided, JSON parsing
    is skipped and an empty dict is returned.
    """
    body = await request.body()
    ts_header = request.headers.get("X-Timestamp")
    sig_header = request.headers.get("X-Signature")
    if not ts_header or not sig_header:
        logger.warning("Auth rejected: missing signature headers | path=%s", request.url.path)
        raise HTTPException(status_code=403, detail="Missing signature headers")
    try:
        timestamp = int(ts_header)
    except ValueError:
        logger.warning("Auth rejected: bad timestamp | path=%s", request.url.path)
        raise HTTPException(status_code=403, detail="Invalid timestamp")

    if require_admin:
        ok = key_store.verify_admin(body, sig_header, timestamp)
        identity = "admin"
    else:
        if client_id_override is not None:
            client_id = str(client_id_override)
        else:
            try:
                payload = json.loads(body)
            except json.JSONDecodeError:
                raise HTTPException(status_code=400, detail="Invalid JSON body")
            client_id = str(payload.get("client_id", ""))
        ok = key_store.verify_client(body, sig_header, client_id, timestamp)
        identity = f"client={client_id}"

    if not ok:
        logger.warning("Auth rejected: bad signature | %s path=%s", identity, request.url.path)
        submit_event(
            "security.auth_rejected",
            client_id=None,
            level="critical",
            context={"identity": identity, "path": request.url.path, "ip": request.client.host if request.client else None},
        )
        raise HTTPException(status_code=403, detail="Invalid signature")
    logger.debug("Auth ok: %s", identity)

    if require_admin or client_id_override is not None:
        return {}
    return payload


@asynccontextmanager
async def lifespan(app):
    logger.info("Application starting | host=%s:%d | model=%s", settings.APP_HOST, settings.APP_PORT, settings.LLM_MODEL)
    async with AsyncExitStack() as stack:
        stack.push_async_callback(executor_cache.close)

        # Register the admin key so admin API calls verify.
        if settings.ADMIN_PUBLIC_KEY:
            key_store.set_admin_key(settings.ADMIN_PUBLIC_KEY)

        # Load client public keys from the shared DB via Laravel. Python has no
        # DB connection, so Laravel is the source of truth and exposes them.
        await _refresh_client_keys()

        # Configure the system-audit event forwarder. When enabled, Python
        # relays its own events and those reported by client Laravel instances
        # to the admin instance's daily system-audit log file.
        if settings.EVENT_FORWARD_ENABLED and settings.ADMIN_LARAVEL_URL:
            # Pass the origin only; the forwarder appends the /api/internal/events path.
            target = settings.ADMIN_LARAVEL_URL.rstrip("/")
            configure_forwarder(target, settings.EVENT_FORWARD_THROTTLE_SECONDS)
            await get_forwarder().start()
            stack.push_async_callback(lambda: asyncio.ensure_future(get_forwarder().stop()))
            logger.info("Event forwarder active | target=%s | throttle=%ss", target, settings.EVENT_FORWARD_THROTTLE_SECONDS)
        else:
            logger.info("Event forwarder disabled")

        SessionManager.cleanup_stale_tmp_files(settings.SESSION_DIR)

        session_manager.start_cleanup()
        stack.push_async_callback(session_manager.shutdown)

        asset_manager.start_cleanup()
        stack.push_async_callback(asset_manager.shutdown)

        await sandbox.prewarm()
        stack.push_async_callback(sandbox.close)

        # Periodically refresh client public keys from Laravel.
        refresh_task = asyncio.create_task(_key_refresh_loop())
        stack.push_async_callback(lambda: refresh_task.cancel())

        # Periodically evict idle executors (refcount 0 past idle TTL).
        evict_task = asyncio.create_task(_executor_evict_loop())
        stack.push_async_callback(lambda: evict_task.cancel())

        yield


async def _refresh_client_keys() -> None:
    """Fetch the client_id -> public_key map from Laravel's internal endpoint.

    Python has no DB connection, so Laravel is the source of truth. The endpoint
    is loopback-only (LocalhostOnly middleware), so no signature is needed.
    Best-effort on failure.
    """
    url = (settings.ADMIN_LARAVEL_URL or "").rstrip("/") + "/api/internal/public-keys"
    if not url.startswith("http"):
        logger.warning("KeyStore refresh skipped: ADMIN_LARAVEL_URL not configured")
        return
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            resp = await client.get(url)
            resp.raise_for_status()
            data = resp.json()
            key_store.refresh_client_keys({str(k): v for k, v in data.get("clients", {}).items()})
    except Exception as e:
        logger.warning("KeyStore refresh failed: %s", e)


async def _key_refresh_loop() -> None:
    """Background loop refreshing client keys every PUBLIC_KEYS_REFRESH_SEC."""
    await asyncio.sleep(2)
    while True:
        await _refresh_client_keys()
        await asyncio.sleep(settings.PUBLIC_KEYS_REFRESH_SEC)


async def _executor_evict_loop() -> None:
    """Background loop closing idle executors every EXECUTOR_EVICT_INTERVAL_SEC."""
    interval = max(30, _EXECUTOR_IDLE_TTL_SEC // 6)
    await asyncio.sleep(interval)
    while True:
        try:
            await executor_cache.evict_idle()
        except Exception:
            logger.exception("ExecutorCache eviction error")
        await asyncio.sleep(interval)


app = FastAPI(title="AI Database Analyst Agent", version="1.0.0", lifespan=lifespan)


@app.middleware("http")
async def telemetry_middleware(request: Request, call_next):
    rid = request.headers.get("X-Request-ID") or uuid.uuid4().hex
    request_id_token = request_id_var.set(rid)
    trace_id_token = trace_id_var.set(request.headers.get("X-Trace-Id") or rid)
    client_id = request.path_params.get("client_id", "-")
    client_id_token = client_id_var.set(client_id)
    request.state.request_id = rid
    request.state.client_id = client_id
    start = time.perf_counter()
    try:
        response = await call_next(request)
        response.headers["X-Request-ID"] = rid
        return response
    finally:
        duration_ms = (time.perf_counter() - start) * 1000
        if duration_ms > 5000:
            logger.warning("Slow request | method=%s path=%s duration_ms=%.0f", request.method, request.url.path, duration_ms)
        request_id_var.reset(request_id_token)
        trace_id_var.reset(trace_id_token)
        client_id_var.reset(client_id_token)


# ── Health check ────────────────────────────────────────────────────────────


@app.get("/health")
async def health():
    return {
        "status": "ok",
        "version": "1.0.0",
        "checks": {"app": "ok"},
        "signature_max_age": settings.SIGNATURE_MAX_AGE_SEC,
        "registered_clients": len(key_store._client_keys),
    }


# ── Internal data endpoints (called by Laravel proxy) ──────────────────────


@app.get("/internal/sessions/{client_id}/{session_id}/history")
async def get_session_history(client_id: str, session_id: str, request: Request):
    await _verify_request(request, require_admin=False, client_id_override=client_id)
    logger.info("GET /internal/sessions/%s/%s/history", client_id, session_id)
    try:
        history = await session_manager.get_history(session_id, client_id)
        session_error = await session_manager.get_session_error(session_id, client_id)
        session = await session_manager.get_or_create(session_id, client_id)
        raw_dfs = session.get("dataframes", {})
        dataframes = {}
        for name, meta in raw_dfs.items():
            shape = meta.get("shape") if isinstance(meta, dict) else getattr(meta, "shape", [0, 0])
            dtypes = meta.get("dtypes") if isinstance(meta, dict) else getattr(meta, "dtypes", [])
            dataframes[name] = {
                "shape": shape,
                "dtypes": dtypes,
                "download_url": f"/internal/sessions/{client_id}/{session_id}/artifacts/{name}/download",
            }
        return {
            "history": history,
            "workspace": {"dataframes": dataframes},
            "session_error": session_error,
        }
    except Exception as e:
        logger.error("Failed to get history for session %s: %s", session_id, e, exc_info=True)
        raise HTTPException(status_code=500, detail="Failed to retrieve session history")


@app.get("/internal/sessions/{client_id}/{session_id}/artifacts/{df_name}/download")
async def download_csv(client_id: str, session_id: str, df_name: str, request: Request):
    await _verify_request(request, require_admin=False, client_id_override=client_id)
    try:
        df = await session_manager.store.get(client_id, session_id, df_name)
    except Exception as e:
        logger.exception("download_csv unexpected error | %s/%s/%s", client_id, session_id, df_name)
        raise HTTPException(status_code=400, detail="Failed to download DataFrame")
    if df is None:
        raise HTTPException(status_code=404, detail="DataFrame not found")
    try:
        csv_text = df.to_csv(index=False)
    except Exception as e:
        logger.warning("download_csv conversion failed | %s/%s/%s | %s", client_id, session_id, df_name, e)
        raise HTTPException(status_code=500, detail="Failed to convert DataFrame to CSV")
    logger.info("download_csv success | %s/%s/%s | rows=%d", client_id, session_id, df_name, len(df))
    return Response(
        content=csv_text,
        media_type="text/csv",
        headers={"Content-Disposition": f'attachment; filename="{df_name}.csv"'},
    )


@app.get("/internal/sessions/{client_id}/{session_id}/assets/{subdir:path}")
async def serve_session_asset(client_id: str, session_id: str, subdir: str, request: Request):
    await _verify_request(request, require_admin=False, client_id_override=client_id)
    filepath = asset_manager.resolve_asset_path(client_id, session_id, *os.path.split(subdir))
    if filepath is None:
        raise HTTPException(status_code=404, detail="Asset not found")
    filename = os.path.basename(filepath)
    media_type = mimetypes.guess_type(filename)[0] or "application/octet-stream"
    logger.info("GET /internal/sessions/%s/%s/assets/%s | serving %s", client_id, session_id, subdir, filename)
    return FileResponse(str(filepath), media_type=media_type, filename=filename)


@app.post("/internal/sessions/{client_id}/{session_id}/cleanup")
async def cleanup_session(client_id: str, session_id: str, request: Request):
    await _verify_request(request, require_admin=False, client_id_override=client_id)
    logger.info("POST /internal/sessions/%s/%s/cleanup", client_id, session_id)
    try:
        await session_manager.delete(session_id, client_id)
        delegation_store.remove(client_id, session_id)
        return {"status": "ok", "client_id": client_id, "session_id": session_id}
    except Exception as e:
        logger.error("Failed to cleanup session %s: %s", session_id, e, exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/internal/analyze")
async def analyze_internal(request: Request):
    payload = await _verify_request(request, require_admin=False)
    try:
        req = QueryRequest(**payload)
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Invalid request: {e}")

    # Lazy client-key refresh: if this client isn't known yet, ask Laravel for
    # the latest key map (handles a brand-new instance before its admin reg).
    if not key_store.has_client(req.client_id):
        await _refresh_client_keys()
        if not key_store.has_client(req.client_id):
            logger.warning("Analyze rejected: unregistered client_id=%s", req.client_id)
            raise HTTPException(status_code=403, detail="Client not registered")

    data_plane_url = req.data_plane_url
    if not data_plane_url:
        raise HTTPException(status_code=400, detail="data_plane_url is required")
    if not data_plane_url.startswith(("http://", "https://")):
        raise HTTPException(status_code=400, detail="data_plane_url must be http:// or https://")

    if not req.delegation_token:
        raise HTTPException(status_code=400, detail="delegation_token is required")

    session_id = req.session_id or str(uuid.uuid4())

    delegation_store.store(req.client_id, session_id, req.delegation_token)

    logger.info("POST /internal/analyze | session=%s | datasource=%s | query=%s", session_id, req.datasource_id or "default", req.query[:100])

    async def event_generator():
        executor = executor_cache.acquire(data_plane_url, req.client_id)
        client_id_token = client_id_var.set(req.client_id)
        trace_id_token = trace_id_var.set(req.trace_id or trace_id_var.get() or "-")
        try:
            async for event in agent.analyze(
                req.query, session_id, req.client_id,
                schema=req.db_schema,
                sensitive_rules=req.sensitive_rules,
                datasource_id=req.datasource_id or "__default__",
                execution=req.execution,
                agent_style=req.agent_style,
                user_ref=req.user_ref,
                user_access=req.user_access,
                executor=executor,
            ):
                if event.get("type") == "error":
                    submit_event(
                        "error.analysis",
                        client_id=req.client_id,
                        level="error",
                        context={
                            "session_id": session_id,
                            "code": event.get("code"),
                            "message": event.get("message"),
                            "trace_id": req.trace_id,
                        },
                    )
                if event.get("type") == "done":
                    _spawn_completion(event.get("meta") or {}, req, session_id)
                yield sse_transport.encode(event)
        except asyncio.CancelledError:
            logger.info("Stream ended for session %s", session_id)
        except Exception as e:
            logger.error("Error in analyze stream: %s", e, exc_info=True)
            payload = stream_error(e)
            yield sse_transport.encode({
                "type": "error",
                "code": payload["code"],
                "message": payload["message"],
                "retryable": payload["retryable"],
                "detail": payload["detail"],
            })
        finally:
            executor_cache.release(data_plane_url)
            client_id_var.reset(client_id_token)
            trace_id_var.reset(trace_id_token)
    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache, no-transform",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
            "X-Content-Type-Options": "nosniff",
        },
    )


# ── System audit events (reported by client Laravel instances) ──────────────
# A client instance forwards its audit events here; Python relays them to the
# admin instance's daily system-audit log file. Authenticated the same way as
# /internal/analyze (Ed25519 signature of the client instance).


class ReportEventBody(BaseModel):
    client_id: Optional[str] = None
    level: str = "info"
    event: str
    context: Dict[str, Any] = {}


@app.post("/api/events")
async def report_event(request: Request):
    payload = await _verify_request(request, require_admin=False)
    try:
        body = ReportEventBody(**payload)
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Invalid request: {e}")

    submit_event(
        body.event,
        client_id=body.client_id,
        level=body.level,
        context=body.context,
        force=True,  # the client already decided to report; don't re-throttle here
    )
    return {"status": "ok"}


# ── Admin API (key management) ──────────────────────────────────────────────
# The admin instance manages the client key store. Every endpoint requires a
# valid admin signature (verified against ADMIN_PUBLIC_KEY).


class RegisterKeyBody(BaseModel):
    client_id: str
    public_key: str


@app.post("/admin/keys/register")
async def admin_register_key(request: Request):
    await _verify_request(request, require_admin=True)
    try:
        body = RegisterKeyBody(**await request.json())
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Invalid request: {e}")
    if not body.public_key or not body.client_id:
        raise HTTPException(status_code=400, detail="client_id and public_key required")
    key_store._client_keys[str(body.client_id)] = body.public_key
    logger.info("Admin: registered key for client_id=%s", body.client_id)
    return {"status": "ok", "client_id": body.client_id}


@app.get("/admin/keys")
async def admin_list_keys(request: Request):
    await _verify_request(request, require_admin=True)
    return {"clients": key_store._client_keys}


@app.delete("/admin/keys/{client_id}")
async def admin_remove_key(client_id: str, request: Request):
    await _verify_request(request, require_admin=True)
    removed = key_store._client_keys.pop(str(client_id), None) is not None
    logger.info("Admin: removed key for client_id=%s (%s)", client_id, removed)
    return {"status": "ok", "removed": removed}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host=settings.APP_HOST, port=settings.APP_PORT, reload=settings.UVICORN_RELOAD, access_log=False)
