"""Ed25519 request signing and verification for instance-to-Python
authentication.

Each Laravel instance (per client) owns an Ed25519 keypair generated by the
admin. The private key never leaves the instance's ``.env``; the public key is
registered in the shared DB (``clients.public_key``) and loaded into this
module's KeyStore at startup.

Signing scheme
--------------
The signed payload is a canonical string ``"<timestamp>:<sha256_hex(body)>"``
sent alongside ``X-Timestamp`` and ``X-Signature`` (hex) headers. This binds the
signature to the exact body bytes and a fresh timestamp (5 min replay window),
so a captured request cannot be replayed or have its body tampered.
"""

import hashlib
import logging
import time
from typing import Optional

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)

logger = logging.getLogger(__name__)

# 5-minute replay window, mirrored on the Laravel side (python-proxy config
# SIGNATURE_MAX_AGE). Driven from Settings so the value is env-configurable
# and can be cross-checked by `php artisan m2m:check`.
from config import get_settings as _get_settings  # noqa: E402

SIGNATURE_MAX_AGE_SEC = int(_get_settings().SIGNATURE_MAX_AGE_SEC)


def _key_private(hex_key: str) -> Ed25519PrivateKey:
    return Ed25519PrivateKey.from_private_bytes(bytes.fromhex(hex_key))


def _key_public(hex_key: str) -> Ed25519PublicKey:
    return Ed25519PublicKey.from_public_bytes(bytes.fromhex(hex_key))


def _canonical(timestamp: int, body: bytes) -> bytes:
    return f"{timestamp}:{hashlib.sha256(body).hexdigest()}".encode()


def sign(body: bytes, private_key: str, timestamp: Optional[int] = None) -> tuple[int, str]:
    """Sign ``body`` with the Ed25519 private key (hex seed).

    Returns ``(timestamp, signature_hex)`` to place in request headers.
    """
    ts = int(time.time()) if timestamp is None else timestamp
    sig = _key_private(private_key).sign(_canonical(ts, body))
    return ts, sig.hex()


def verify(body: bytes, signature_hex: str, public_key: str, timestamp: int, max_age: int = SIGNATURE_MAX_AGE_SEC) -> bool:
    """Verify an Ed25519 signature over ``body``.

    Returns ``False`` (never raises) on a missing/expired timestamp, a malformed
    key, or a bad signature — all of which mean "reject this request".
    """
    try:
        if abs(int(time.time()) - timestamp) > max_age:
            return False
        _key_public(public_key).verify(bytes.fromhex(signature_hex), _canonical(timestamp, body))
        return True
    except (InvalidSignature, ValueError, TypeError):
        return False


class KeyStore:
    """In-memory registry of verified public keys, loaded from Laravel.

    Python never opens a DB connection; Laravel is the source of truth and pushes
    the key map to us via :meth:`refresh` (called at startup and on a timer).
    """

    def __init__(self) -> None:
        self._client_keys: dict[str, str] = {}
        self._admin_key: Optional[str] = None

    # -- loading ----------------------------------------------------------------

    def refresh_client_keys(self, keys: dict[str, str]) -> None:
        """Replace the client key map. ``keys`` maps client_id -> public_key_hex."""
        changed = keys != self._client_keys
        self._client_keys = dict(keys)
        if changed:
            logger.info("KeyStore: loaded %d client public key(s)", len(self._client_keys))
        else:
            logger.debug("KeyStore: %d client public key(s) unchanged", len(self._client_keys))

    def set_admin_key(self, public_key: str) -> None:
        """Set the single admin instance public key (loaded from local file)."""
        self._admin_key = public_key
        logger.info("KeyStore: admin public key registered")

    # -- verification -----------------------------------------------------------

    def verify_client(self, body: bytes, signature_hex: str, client_id: str, timestamp: int, max_age: int = SIGNATURE_MAX_AGE_SEC) -> bool:
        """True iff ``client_id`` is known and its key validates the signature."""
        key = self._client_keys.get(str(client_id))
        if key is None:
            logger.warning("KeyStore: unknown client_id=%s", client_id)
            return False
        return verify(body, signature_hex, key, timestamp, max_age)

    def verify_admin(self, body: bytes, signature_hex: str, timestamp: int, max_age: int = SIGNATURE_MAX_AGE_SEC) -> bool:
        """True iff an admin key is set and validates the signature."""
        if self._admin_key is None:
            logger.warning("KeyStore: no admin key configured")
            return False
        return verify(body, signature_hex, self._admin_key, timestamp, max_age)

    # -- introspection ----------------------------------------------------------

    @property
    def client_ids(self) -> set[str]:
        return set(self._client_keys.keys())

    def has_client(self, client_id: str) -> bool:
        return str(client_id) in self._client_keys


# Process-wide singleton. Importers use ``from agent.auth import key_store``.
key_store = KeyStore()
